/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2022 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "adc.h"
#include "dma.h"
#include "tim.h"
#include "usart.h"
#include "gpio.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */

#include "lib/sm_bypass.h"
#include "lib/led.h"
#include "lib/wavetable_gen.h"
#include "lib/param.h"


/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

typedef struct {
	uint32_t *Rate;
	uint32_t *Depth;
	uint32_t *Shape;
	uint32_t *Offset;
	uint32_t *Subdiv;
	uint32_t *Exp;
	uint32_t *Trim1;
	uint32_t *Trim2;
	uint32_t *Vol;
} Adc;

typedef enum {
	STATE_STD,
	STATE_HARM,
	STATE_PAN,
} StatePhase;

typedef enum {
	EVENT_STD,
	EVENT_HARM,
	EVENT_PAN,
} EventPhase;

struct params {
	struct Param rate;
	struct Param depth;
	struct Param offset;
	struct Param phase;
	struct Param vol;
} ;

struct subdiv {
	uint32_t num;
	uint32_t denom;
};



/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */
/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/

/* USER CODE BEGIN PV */


/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
/* USER CODE BEGIN PFP */

// INIT FUNCTIONS
void init_adc_channels(Adc*, uint32_t[]);
void init_LEDs(LED*, LED*);
void start_dma();
void start_pwm_oc();

// PARAM GETTERS
void get_rate();
EventPhase get_phase();
Shape get_shape();
struct subdiv get_subdiv();
void get_volume();

// PARAM SETTERS
void set_rate(float, struct subdiv);
void set_volume(float);

// CALLBACKS
void My_DMA_XferCpltCallback(DMA_HandleTypeDef*);
void My_DMA_XferHalfCpltCallback(DMA_HandleTypeDef*);


/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

uint32_t adc_array[ADC_DMA_BUF_LENGTH] = {0};
Adc adc_raw;

uint16_t dma_wavetable_a[WAVETABLE_WIDTH] = {0};
uint16_t dma_wavetable_b[WAVETABLE_WIDTH] = {0};

LED LED_bypass;
LED LED_tap;



/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* Iniitalize state machines */
  StateBypassSw state_bypass_sw = STATE_IDLE;
  StateEffect state_effect = STATE_BYPASS;
  StateRelayMute state_relay_mute = STATE_BYPASS_UNMUTE;
  // TODO get rid of the event/state dichotomy. Copy what Shape does.
  StatePhase state_phase = STATE_STD;
  EventPhase phase_sw = EVENT_STD;
  Shape shape = ERR;
  struct subdiv subdiv = {.num = 1, .denom = 4};

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */
  // Needs to be done first to fix bug in autogenerated code X_X
  MX_DMA_Init();
  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_ADC1_Init();
  MX_TIM2_Init();
  MX_TIM3_Init();
  MX_DMA_Init();
  MX_USART1_UART_Init();
  MX_TIM4_Init();
  MX_TIM8_Init();
  /* USER CODE BEGIN 2 */

  init_LEDs(&LED_bypass, &LED_tap);
  init_adc_channels(&adc_raw, adc_array);
  start_dma();
  start_pwm_oc();

  // Initialize Parameters
  // TODO use macros for min/max values
  // TODO move to function / clean up. Globals?
  struct Param rate = {
  		  .val = adc_raw.Rate,
  		  .map_func = map_rate_pseudo_log,
  		  .val_min = 0,
  		  .val_max = ADC_RESOLUTION,
  		  .map_min = RATE_ARR_MIN,
  		  .map_max = RATE_ARR_MAX,
		  .invert = 1
  };
  struct Param depth = {
  		  .val = adc_raw.Depth,
  		  .map_func = map_param_lin,
  		  .val_min = 0,
  		  .val_max = ADC_RESOLUTION,
  		  .map_min = 0,
  		  .map_max = 1,
		  .invert = 0
  };
  struct Param offset = {
    		  .val = adc_raw.Offset,
    		  .map_func = map_param_lin,
    		  .val_min = 0,
    		  .val_max = ADC_RESOLUTION,
    		  .map_min = 0,
    		  .map_max = 1,
			  .invert = 0
  };
  struct Param phase = {
    		  .val = adc_raw.Shape,
    		  .map_func = map_param_lin,
    		  .val_min = 0,
    		  .val_max = ADC_RESOLUTION,
    		  .map_min = 0,
    		  .map_max = 1,
			  .invert = 0
  };
  struct Param vol = {
    		  .val = adc_raw.Vol,
    		  .map_func = map_param_lin,
    		  .val_min = 0,
    		  .val_max = ADC_RESOLUTION,
    		  .map_min = VOL_MAP_MIN,
    		  .map_max = VOL_MAP_MAX,
			  .invert = 1
  };
  struct Param sense = {
    		  .val = adc_raw.Subdiv,
    		  .map_func = map_param_lin,
    		  .val_min = 0,
    		  .val_max = ADC_RESOLUTION,
    		  .map_min = 0,
    		  .map_max = 1,
			  .invert = 0
  };
  struct Param env = {
    		  .val = adc_raw.Trim1,
    		  .map_func = map_param_lin,
    		  .val_min = 0,
    		  .val_max = ADC_RESOLUTION,
    		  .map_min = 0,
    		  .map_max = 1,
			  .invert = 0
  };

  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
	  //rate = *adc_raw.Rate;
	  //depth = *adc_raw.Depth;
	  //offset = *adc_raw.Offset;
	  //env = *adc_raw.Trim1;
	  //phase = *adc_raw.Shape;

	  // Read inputs
	  // TODO do I want a get function for ADC inputs?
	  get_rate();
	  subdiv = get_subdiv();
	  get_volume();
	  shape = get_shape();
	  // Set things based on parameters
	  set_rate(rate.map_func(&rate), subdiv);
	  set_volume(vol.map_func(&vol));
	  // Generate wavetable
	  wavetable_gen(shape,
			  depth.map_func(&depth),
			  offset.map_func(&offset),
			  phase.map_func(&phase),
			  dma_wavetable_a, WAVETABLE_WIDTH, WAVETABLE_DEPTH);


	  // Check for bypass switch state and run state machine
	  // TODO make this cleaner
	  EventBypassSw event_bypass_sw = EVENT_RELEASED;
	  if (!HAL_GPIO_ReadPin(pDIN_BYP_GPIO_Port, pDIN_BYP_Pin)){
		  event_bypass_sw = EVENT_PRESSED;
	  }
	  sm_bypass_sw(&state_bypass_sw, event_bypass_sw, &state_effect);

	  EventRelayMute event_relay_mute = EVENT_BYPASS;
	  if (state_effect == STATE_EFFECT){
		  event_relay_mute = EVENT_EFFECT;
	  }

	  sm_relay_mute(&state_relay_mute, event_relay_mute, &LED_bypass);


	  // TODO move this to a function
	  if (!HAL_GPIO_ReadPin(pDIN_ENV_MODE_1_GPIO_Port,
			  pDIN_ENV_MODE_1_Pin)){
		  // Toggle to left, envelope controls Rate
		  rate.map_max = ENV_MAX;
		  rate.val = adc_raw.Trim1;
		  set_LED_color(&LED_bypass, RED);
	  }
	  else if (!HAL_GPIO_ReadPin(pDIN_ENV_MODE_2_GPIO_Port,
			  pDIN_ENV_MODE_2_Pin)){
		  // Toggle to right, envelope controls Depth
		  // TODO reconcile uint and float differences
		  //depth.map_max = ENV_MAX;
		  //depth.val = adc_raw.Trim1;
		  set_LED_color(&LED_bypass, BLUE);
	  }
	  else {
		  // Toggle in middle, no envelope control
		  set_LED_color(&LED_bypass, GREEN);
	  }


  }
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
  RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL4;
  RCC_OscInitStruct.PLL.PREDIV = RCC_PREDIV_DIV1;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1) != HAL_OK)
  {
    Error_Handler();
  }
  PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_USART1|RCC_PERIPHCLK_TIM8
                              |RCC_PERIPHCLK_ADC12|RCC_PERIPHCLK_TIM2
                              |RCC_PERIPHCLK_TIM34;
  PeriphClkInit.Usart1ClockSelection = RCC_USART1CLKSOURCE_PCLK2;
  PeriphClkInit.Adc12ClockSelection = RCC_ADC12PLLCLK_DIV8;
  PeriphClkInit.Tim8ClockSelection = RCC_TIM8CLK_PLLCLK;
  PeriphClkInit.Tim2ClockSelection = RCC_TIM2CLK_PLLCLK;
  PeriphClkInit.Tim34ClockSelection = RCC_TIM34CLK_PLLCLK;
  if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK)
  {
    Error_Handler();
  }
}

/* USER CODE BEGIN 4 */

/*
 * 	INIT/START FUNCTIONS
 */

void start_dma()
{
	if (HAL_ADC_Start_DMA(&hadc1, adc_array, ADC_DMA_BUF_LENGTH) != HAL_OK)
	{
		Error_Handler();
	}

	// Link Transfer complete callback to DMA handle:
	HDMA_WVFM_A_LO.XferCpltCallback = My_DMA_XferCpltCallback;
	HDMA_WVFM_A_LO.XferHalfCpltCallback = My_DMA_XferHalfCpltCallback;
	HDMA_WVFM_A_HI.XferCpltCallback = My_DMA_XferCpltCallback;
	HDMA_WVFM_A_HI.XferHalfCpltCallback = My_DMA_XferHalfCpltCallback;
	HDMA_WVFM_B_LO.XferCpltCallback = My_DMA_XferCpltCallback;
	HDMA_WVFM_B_LO.XferHalfCpltCallback = My_DMA_XferHalfCpltCallback;
	HDMA_WVFM_B_HI.XferCpltCallback = My_DMA_XferCpltCallback;
	HDMA_WVFM_B_HI.XferHalfCpltCallback = My_DMA_XferHalfCpltCallback;

	// First just setting all 4 channels synced to same wavetable
	__HAL_TIM_ENABLE_DMA(&HTIM_WVFM_A_LO, TIM_DMA_CC1);
	__HAL_TIM_ENABLE_DMA(&HTIM_WVFM_A_HI, TIM_DMA_CC2);
	__HAL_TIM_ENABLE_DMA(&HTIM_WVFM_B_LO, TIM_DMA_CC3);
	__HAL_TIM_ENABLE_DMA(&HTIM_WVFM_B_HI, TIM_DMA_CC4);
	__HAL_DMA_ENABLE_IT(&HDMA_WVFM_A_LO, DMA_IT_HT);
	__HAL_DMA_ENABLE_IT(&HDMA_WVFM_A_HI, DMA_IT_HT);
	__HAL_DMA_ENABLE_IT(&HDMA_WVFM_B_LO, DMA_IT_HT);
	__HAL_DMA_ENABLE_IT(&HDMA_WVFM_B_HI, DMA_IT_HT);
	HAL_DMA_Start_IT(&HDMA_WVFM_A_LO, (uint32_t)dma_wavetable_a,
			(uint32_t)&DMA_DST_PWM_A_LO, WAVETABLE_WIDTH);
	HAL_DMA_Start_IT(&HDMA_WVFM_A_HI, (uint32_t)dma_wavetable_b,
			(uint32_t)&DMA_DST_PWM_A_HI, WAVETABLE_WIDTH);
	HAL_DMA_Start_IT(&HDMA_WVFM_B_LO, (uint32_t)dma_wavetable_a,
			(uint32_t)&DMA_DST_PWM_B_LO, WAVETABLE_WIDTH);
	HAL_DMA_Start_IT(&HDMA_WVFM_B_HI, (uint32_t)dma_wavetable_b,
			(uint32_t)&DMA_DST_PWM_B_HI, WAVETABLE_WIDTH);

	/*
	  // Enable transfer complete interrupts
	  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch1, DMA_IT_TC);
	  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch2, DMA_IT_TC);
	  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch3_up, DMA_IT_TC);
	  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch4_trig_com, DMA_IT_TC);
	  // Enable transfer half complete interrupts
	  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch1, DMA_IT_HT);
	  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch2, DMA_IT_HT);
	  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch3_up, DMA_IT_HT);
	  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch4_trig_com, DMA_IT_HT);
	*/

	return;
}

void start_pwm_oc()
{
	// Start PWM for Volume outputs
	if ((HAL_TIM_PWM_Start(&HTIM_VOL_A, TIM_CH_VOL_A) |
		  HAL_TIM_PWM_Start(&HTIM_VOL_B, TIM_CH_VOL_B)) != HAL_OK)
	{
		Error_Handler();
	}
	// Start PWM output for PWM timers (the ones that actually output the LFOs)
	if ((HAL_TIM_PWM_Start(&HTIM_PWM_A_LO, TIM_CH_PWM_A_LO) |
			HAL_TIM_PWM_Start(&HTIM_PWM_A_HI, TIM_CH_PWM_A_HI) |
			HAL_TIM_PWM_Start(&HTIM_PWM_B_LO, TIM_CH_PWM_B_LO) |
			HAL_TIM_PWM_Start(&HTIM_PWM_B_HI, TIM_CH_PWM_B_HI)) != HAL_OK)
	{
		Error_Handler();
	}
	// Start output compare for waveform timers (to update the wavetables)
	if ((HAL_TIM_OC_Start(&HTIM_WVFM_A_LO, TIM_CH_WVFM_A_LO) |
		HAL_TIM_OC_Start(&HTIM_WVFM_A_HI, TIM_CH_WVFM_A_HI) |
		HAL_TIM_OC_Start(&HTIM_WVFM_B_LO, TIM_CH_WVFM_B_LO) |
		HAL_TIM_OC_Start(&HTIM_WVFM_B_HI, TIM_CH_WVFM_B_HI)) != HAL_OK)
	{
		Error_Handler();
	}
	return;
}

void init_params()
{
	return;
}

// This maps named Adc struct members to the DMA buffer for convenience
void init_adc_channels(Adc *adc, uint32_t adc_buffer[]){
	adc->Rate = &adc_buffer[0];
	adc->Depth = &adc_buffer[1];
	adc->Shape = &adc_buffer[2];
	adc->Offset = &adc_buffer[3];
	adc->Subdiv = &adc_buffer[4];
	adc->Exp = &adc_buffer[5];
	adc->Trim1 = &adc_buffer[6];
	adc->Trim2 = &adc_buffer[7];
	adc->Vol = &adc_buffer[8];
}

// Initialize LEDs with GPIO ports/pins, and set default states
void init_LEDs(LED* LED_bypass, LED* LED_tap){
	initLED(LED_tap, GREEN, OFF,
			pDOUT_LED1_R_GPIO_Port, pDOUT_LED1_R_Pin,
			pDOUT_LED1_G_GPIO_Port, pDOUT_LED1_G_Pin,
			pDOUT_LED1_B_GPIO_Port, pDOUT_LED1_B_Pin);
	initLED(LED_bypass, GREEN, OFF,
			pDOUT_LED2_R_GPIO_Port, pDOUT_LED2_R_Pin,
			pDOUT_LED2_G_GPIO_Port, pDOUT_LED2_G_Pin,
			pDOUT_LED2_B_GPIO_Port, pDOUT_LED2_B_Pin);
}

/*
 * 	GET FUNCTIONS
 */


// Set things based on parameters

void get_rate()
{
	return;
}

struct subdiv get_subdiv()
{
	struct subdiv subdiv;
	uint32_t ph_right = HAL_GPIO_ReadPin(pDIN_HARM_MODE_1_GPIO_Port,
			  pDIN_HARM_MODE_1_Pin);
	uint32_t ph_left = HAL_GPIO_ReadPin(pDIN_HARM_MODE_2_GPIO_Port,
			  pDIN_HARM_MODE_2_Pin);
	if (!ph_left)
	{
		subdiv.num = 1;
		subdiv.denom = QUARTER;
	}
	else if (!ph_right)
	{
		subdiv.num = 1;
		subdiv.denom = EIGHTH;
	}
	else
	{
		subdiv.num = 1;
		subdiv.denom = TRIPLET;
	}
	return subdiv;
}

// No longer used, this is a knob now
EventPhase get_phase(StatePhase* state, LED* LED_bypass){
	  uint32_t ph_right = HAL_GPIO_ReadPin(pDIN_HARM_MODE_1_GPIO_Port,
			  pDIN_HARM_MODE_1_Pin);
	  uint32_t ph_left = HAL_GPIO_ReadPin(pDIN_HARM_MODE_2_GPIO_Port,
			  pDIN_HARM_MODE_2_Pin);
	  if (!ph_left){ return EVENT_PAN; }
	  else if (!ph_right){ return EVENT_HARM; }
	  else { return EVENT_STD; }
}


Shape get_shape()
{
	uint32_t right = HAL_GPIO_ReadPin(pDIN_PAN_MODE_1_GPIO_Port,
			pDIN_PAN_MODE_1_Pin);
	uint32_t left = HAL_GPIO_ReadPin(pDIN_PAN_MODE_2_GPIO_Port,
			pDIN_PAN_MODE_2_Pin);
	if (!left) { return SINE; }
	else if (!right) { return SQUR; }
	else { return TRI; }
}

void get_volume()
{
	return;
}


/*
 * 	SET FUNCTIONS
 */

/**
 * @brief Sets timer registers based on rate & subdivision inputs
 *
 * Prescaler and ARR get set 4x for the sake of code portability.
 * Could be made more efficient with some clever macros.
 *
 * @param rate Base quarter note LFO rate
 * @param subdiv Note subdivision, e.g. quarter, eighth, triplet
 */
void set_rate(float rate, struct subdiv subdiv){
	// Set prescaler based on subdiv
	uint32_t prsclr = PWM_TIM_PRSCLR_BASE * QUARTER * subdiv.num / subdiv.denom;
	__HAL_TIM_SET_PRESCALER(&HTIM_WVFM_A_LO, prsclr);
	__HAL_TIM_SET_PRESCALER(&HTIM_WVFM_A_HI, prsclr);
	__HAL_TIM_SET_PRESCALER(&HTIM_WVFM_B_LO, prsclr);
	__HAL_TIM_SET_PRESCALER(&HTIM_WVFM_B_HI, prsclr);
	// Set ARR based on rate
	__HAL_TIM_SET_AUTORELOAD(&HTIM_WVFM_A_LO, (uint32_t)rate);
	__HAL_TIM_SET_AUTORELOAD(&HTIM_WVFM_A_HI, (uint32_t)rate);
	__HAL_TIM_SET_AUTORELOAD(&HTIM_WVFM_B_LO, (uint32_t)rate);
	__HAL_TIM_SET_AUTORELOAD(&HTIM_WVFM_B_HI, (uint32_t)rate);
}

void set_volume(float vol){
	__HAL_TIM_SET_COMPARE(&HTIM_VOL_A, TIM_CH_VOL_A, (uint16_t)vol);
	__HAL_TIM_SET_COMPARE(&HTIM_VOL_B, TIM_CH_VOL_B, (uint16_t)vol);
}

/*
 * CALLBACKS
 */

void HAL_TIM_IC_CaptureCallback(TIM_HandleTypeDef *htim)
{

}

void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef* hadc)
{

}

void My_DMA_XferHalfCpltCallback(DMA_HandleTypeDef *hdma)
{
	// TODO don't call function from interrupt
	set_LED_state(&LED_tap, OFF);
	return;
}

void My_DMA_XferCpltCallback(DMA_HandleTypeDef *hdma)
{
	set_LED_state(&LED_tap, ON);
	return;
}


/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();

  HAL_GPIO_WritePin(pDOUT_LED2_B_GPIO_Port, pDOUT_LED2_B_Pin, LED_PIN_SET);
  HAL_GPIO_WritePin(pDOUT_LED2_R_GPIO_Port, pDOUT_LED2_R_Pin, LED_PIN_SET);
  HAL_GPIO_WritePin(pDOUT_LED2_G_GPIO_Port, pDOUT_LED2_G_Pin, LED_PIN_SET);
  HAL_GPIO_WritePin(pDOUT_LED1_B_GPIO_Port, pDOUT_LED1_B_Pin, LED_PIN_SET);
  HAL_GPIO_WritePin(pDOUT_LED1_R_GPIO_Port, pDOUT_LED1_R_Pin, LED_PIN_SET);
  HAL_GPIO_WritePin(pDOUT_LED1_G_GPIO_Port, pDOUT_LED1_G_Pin, LED_PIN_SET);

  while (1)
  {
	  HAL_Delay(250);

	  HAL_GPIO_TogglePin(pDOUT_LED2_B_GPIO_Port, pDOUT_LED2_B_Pin);
	  HAL_GPIO_TogglePin(pDOUT_LED2_R_GPIO_Port, pDOUT_LED2_R_Pin);
	  HAL_GPIO_TogglePin(pDOUT_LED2_G_GPIO_Port, pDOUT_LED2_G_Pin);
	  HAL_GPIO_TogglePin(pDOUT_LED1_B_GPIO_Port, pDOUT_LED1_B_Pin);
	  HAL_GPIO_TogglePin(pDOUT_LED1_R_GPIO_Port, pDOUT_LED1_R_Pin);
	  HAL_GPIO_TogglePin(pDOUT_LED1_G_GPIO_Port, pDOUT_LED1_G_Pin);

  }
  /* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
