/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2022 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
/* USER CODE END Header */
/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "adc.h"
#include "dma.h"
#include "tim.h"
#include "usart.h"
#include "gpio.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */

#include "lib/sm_bypass.h"
#include "lib/led.h"
#include "lib/wavetable_gen.h"
#include "lib/param.h"


/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

typedef struct {
	uint32_t *Rate;
	uint32_t *Depth;
	uint32_t *Shape;
	uint32_t *Offset;
	uint32_t *Subdiv;
	uint32_t *Exp;
	uint32_t *Trim1;
	uint32_t *Trim2;
	uint32_t *Vol;
} Adc;

typedef enum {
	STATE_STD,
	STATE_HARM,
	STATE_PAN,
} StatePhase;

typedef enum {
	EVENT_STD,
	EVENT_HARM,
	EVENT_PAN,
} EventPhase;



/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */
/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/

/* USER CODE BEGIN PV */

LED LED_bypass;
LED LED_tap;

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
/* USER CODE BEGIN PFP */

void led_toggle_tick(uint32_t, GPIO_TypeDef*, uint16_t);
void generate_triangle_wave_fixedpoint(uint32_t, uint32_t);
void generate_triangle_wave_floatingpoint(uint32_t, uint32_t);

void init_adc_channels(Adc*, uint32_t[]);
void init_LEDs(LED*, LED*);
void set_lfo_polarity();
void set_volume(uint16_t);
void set_rate(float);
void set_phase(StatePhase*, LED*);
void set_shape(Shape*);
void sm_phase(StatePhase*, EventPhase, LED*);
uint32_t env_map(uint32_t);

void My_DMA_XferCpltCallback(DMA_HandleTypeDef*);
void My_DMA_XferHalfCpltCallback(DMA_HandleTypeDef*);


/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

uint32_t adc_array[ADC_DMA_BUF_LENGTH] = {0};

uint16_t dma_wavetable_a[WAVETABLE_WIDTH] = {0};
uint16_t dma_wavetable_b[WAVETABLE_WIDTH] = {0};

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* Iniitalize state machines */
  StateBypassSw state_bypass_sw = STATE_IDLE;
  StateEffect state_effect = STATE_BYPASS;
  StateRelayMute state_relay_mute = STATE_BYPASS_UNMUTE;
  StatePhase state_phase = STATE_STD;
  Shape shape = ERR;

  init_LEDs(&LED_bypass, &LED_tap);

  Adc adc_raw;
  init_adc_channels(&adc_raw, adc_array);

  //uint32_t rate = *adc_raw.Rate;
  //uint32_t depth = *adc_raw.Depth;
  //uint32_t offset = *adc_raw.Offset;
  uint32_t vol = *adc_raw.Vol;
  //uint32_t env = *adc_raw.Trim1;
  // TODO rename this adc parameter
  //uint32_t phase = *adc_raw.Shape;

  struct Param rate  = param_init(adc_raw.Rate, RATE_ARR_MIN, RATE_ARR_MAX, 0, ADC_RESOLUTION, 1);
  struct Param depth = param_init(adc_raw.Depth, 0, 1, 0, ADC_RESOLUTION, 0);
  struct Param offset = param_init(adc_raw.Offset, 0, 1, 0, ADC_RESOLUTION, 0);
  struct Param phase = param_init(adc_raw.Shape, 0, 1, 0, ADC_RESOLUTION, 0);

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */
  // Needs to be done first to fix bug in autogenerated code X_X
  MX_DMA_Init();
  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_ADC1_Init();
  MX_TIM2_Init();
  MX_TIM3_Init();
  MX_DMA_Init();
  MX_USART1_UART_Init();
  MX_TIM4_Init();
  MX_TIM8_Init();
  /* USER CODE BEGIN 2 */

  // TODO clean up and move to function
  if (HAL_ADC_Start_DMA(&hadc1, adc_array,
		  ADC_DMA_BUF_LENGTH) != HAL_OK)
  {
	  Error_Handler();
  }

  // Start PWM for Volume outputs
  if ((HAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_1) |
	  HAL_TIM_PWM_Start(&htim2, TIM_CHANNEL_2)) != HAL_OK)
  {
	  Error_Handler();
  }



  // Start PWM output for PWM timers (the ones that actually output the LFOs)
  if ((HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_1) |
	  HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_2) |
	  HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_3) |
	  HAL_TIM_PWM_Start(&htim3, TIM_CHANNEL_4)) != HAL_OK)
  {
	  Error_Handler();
  }

  // Link Transfer complete callback to DMA handle:
  hdma_tim8_ch1.XferCpltCallback = My_DMA_XferCpltCallback;
  hdma_tim8_ch1.XferHalfCpltCallback = My_DMA_XferHalfCpltCallback;
  hdma_tim8_ch2.XferCpltCallback = My_DMA_XferCpltCallback;
  hdma_tim8_ch2.XferHalfCpltCallback = My_DMA_XferHalfCpltCallback;
  hdma_tim8_ch3_up.XferCpltCallback = My_DMA_XferCpltCallback;
  hdma_tim8_ch3_up.XferHalfCpltCallback = My_DMA_XferHalfCpltCallback;
  hdma_tim8_ch4_trig_com.XferCpltCallback = My_DMA_XferCpltCallback;
  hdma_tim8_ch4_trig_com.XferHalfCpltCallback = My_DMA_XferHalfCpltCallback;

  // First just setting all 4 channels synced to same wavetable
  // TODO figure out best way to have different phases per channel
  __HAL_TIM_ENABLE_DMA(&htim8, TIM_DMA_CC1);
  __HAL_TIM_ENABLE_DMA(&htim8, TIM_DMA_CC2);
  __HAL_TIM_ENABLE_DMA(&htim8, TIM_DMA_CC3);
  __HAL_TIM_ENABLE_DMA(&htim8, TIM_DMA_CC4);
  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch1, DMA_IT_HT);
  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch2, DMA_IT_HT);
  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch3_up, DMA_IT_HT);
  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch4_trig_com, DMA_IT_HT);
  HAL_DMA_Start_IT(&hdma_tim8_ch1, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR1), WAVETABLE_WIDTH);
  HAL_DMA_Start_IT(&hdma_tim8_ch2, (uint32_t)dma_wavetable_b, (uint32_t)&(TIM3->CCR2), WAVETABLE_WIDTH);
  HAL_DMA_Start_IT(&hdma_tim8_ch3_up, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR3), WAVETABLE_WIDTH);
  HAL_DMA_Start_IT(&hdma_tim8_ch4_trig_com, (uint32_t)dma_wavetable_b, (uint32_t)&(TIM3->CCR4), WAVETABLE_WIDTH);

  // Start output compare for waveform timers (to update the wavetables)
  if ((HAL_TIM_OC_Start(&htim8, TIM_CHANNEL_1) |
	  HAL_TIM_OC_Start(&htim8, TIM_CHANNEL_2) |
	  HAL_TIM_OC_Start(&htim8, TIM_CHANNEL_3) |
	  HAL_TIM_OC_Start(&htim8, TIM_CHANNEL_4)) != HAL_OK)
  {
	  Error_Handler();
  }

/*
  // Enable transfer complete interrupts
  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch1, DMA_IT_TC);
  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch2, DMA_IT_TC);
  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch3_up, DMA_IT_TC);
  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch4_trig_com, DMA_IT_TC);
  // Enable transfer half complete interrupts
  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch1, DMA_IT_HT);
  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch2, DMA_IT_HT);
  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch3_up, DMA_IT_HT);
  __HAL_DMA_ENABLE_IT(&hdma_tim8_ch4_trig_com, DMA_IT_HT);
*/



  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {
	  //rate = *adc_raw.Rate;
	  //depth = *adc_raw.Depth;
	  //offset = *adc_raw.Offset;
	  vol = *adc_raw.Vol;
	  //env = *adc_raw.Trim1;
	  //phase = *adc_raw.Shape;

	  // Read inputs
	  // TODO move inputs to another file
	  set_rate(rate.map_val(&rate));
	  set_volume(vol);
	  set_phase(&state_phase, &LED_tap);
	  set_shape(&shape);

	  // Check for bypass switch state and run state machine
	  EventBypassSw event_bypass_sw = EVENT_RELEASED;
	  if (!HAL_GPIO_ReadPin(pDIN_BYP_GPIO_Port, pDIN_BYP_Pin)){
		  event_bypass_sw = EVENT_PRESSED;
	  }
	  sm_bypass_sw(&state_bypass_sw, event_bypass_sw, &state_effect);

	  EventRelayMute event_relay_mute = EVENT_BYPASS;
	  if (state_effect == STATE_EFFECT){
		  event_relay_mute = EVENT_EFFECT;
	  }

	  sm_relay_mute(&state_relay_mute, event_relay_mute, &LED_bypass);


	  // Generate wavetable
	  wavetable_gen(shape,
			  depth.map_val(&depth),
			  offset.map_val(&offset),
			  phase.map_val(&phase),
			  dma_wavetable_a, WAVETABLE_WIDTH, WAVETABLE_DEPTH);

	  // TODO move this to a function
	  if (!HAL_GPIO_ReadPin(pDIN_ENV_MODE_1_GPIO_Port,
			  pDIN_ENV_MODE_1_Pin)){
		  // Toggle to left, envelope controls Rate
		  rate.map_max = ENV_MAX;
		  rate.val = adc_raw.Trim1;
		  set_LED_color(&LED_bypass, RED);
	  }
	  else if (!HAL_GPIO_ReadPin(pDIN_ENV_MODE_2_GPIO_Port,
			  pDIN_ENV_MODE_2_Pin)){
		  // Toggle to right, envelope controls Depth
		  depth.map_max = ENV_MAX;
		  depth.val = adc_raw.Trim1;
		  set_LED_color(&LED_bypass, BLUE);
	  }
	  else {
		  // Toggle in middle, no envelope control
		  set_LED_color(&LED_bypass, GREEN);
	  }


  }
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
  /* USER CODE END 3 */
}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};
  RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLMUL = RCC_PLL_MUL4;
  RCC_OscInitStruct.PLL.PREDIV = RCC_PREDIV_DIV1;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1) != HAL_OK)
  {
    Error_Handler();
  }
  PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_USART1|RCC_PERIPHCLK_TIM8
                              |RCC_PERIPHCLK_ADC12|RCC_PERIPHCLK_TIM2
                              |RCC_PERIPHCLK_TIM34;
  PeriphClkInit.Usart1ClockSelection = RCC_USART1CLKSOURCE_PCLK2;
  PeriphClkInit.Adc12ClockSelection = RCC_ADC12PLLCLK_DIV8;
  PeriphClkInit.Tim8ClockSelection = RCC_TIM8CLK_PLLCLK;
  PeriphClkInit.Tim2ClockSelection = RCC_TIM2CLK_PLLCLK;
  PeriphClkInit.Tim34ClockSelection = RCC_TIM34CLK_PLLCLK;
  if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK)
  {
    Error_Handler();
  }
}

/* USER CODE BEGIN 4 */

// This maps named Adc struct members to the DMA buffer for convenience
void init_adc_channels(Adc *adc, uint32_t adc_buffer[]){
	adc->Rate = &adc_buffer[0];
	adc->Depth = &adc_buffer[1];
	adc->Shape = &adc_buffer[2];
	adc->Offset = &adc_buffer[3];
	adc->Subdiv = &adc_buffer[4];
	adc->Exp = &adc_buffer[5];
	adc->Trim1 = &adc_buffer[6];
	adc->Trim2 = &adc_buffer[7];
	adc->Vol = &adc_buffer[8];
}

// Initialize LEDs with GPIO ports/pins, and set default states
void init_LEDs(LED* LED_bypass, LED* LED_tap){
	initLED(LED_tap, GREEN, OFF,
			pDOUT_LED1_R_GPIO_Port, pDOUT_LED1_R_Pin,
			pDOUT_LED1_G_GPIO_Port, pDOUT_LED1_G_Pin,
			pDOUT_LED1_B_GPIO_Port, pDOUT_LED1_B_Pin);
	initLED(LED_bypass, GREEN, OFF,
			pDOUT_LED2_R_GPIO_Port, pDOUT_LED2_R_Pin,
			pDOUT_LED2_G_GPIO_Port, pDOUT_LED2_G_Pin,
			pDOUT_LED2_B_GPIO_Port, pDOUT_LED2_B_Pin);
}

// TODO move to another file
// TODO see if these can be genericised
void set_phase(StatePhase* state, LED* LED_bypass){
	  uint32_t ph_right = HAL_GPIO_ReadPin(pDIN_HARM_MODE_1_GPIO_Port,
			  pDIN_HARM_MODE_1_Pin);
	  uint32_t ph_left = HAL_GPIO_ReadPin(pDIN_HARM_MODE_2_GPIO_Port,
			  pDIN_HARM_MODE_2_Pin);
	  if (!ph_left){sm_phase(state, EVENT_PAN, LED_bypass);}
	  else if (!ph_right){sm_phase(state, EVENT_HARM, LED_bypass);}
	  else {sm_phase(state, EVENT_STD, LED_bypass);}
}

void set_shape(Shape* shape)
{
	uint32_t right = HAL_GPIO_ReadPin(pDIN_PAN_MODE_1_GPIO_Port,
			pDIN_PAN_MODE_1_Pin);
	uint32_t left = HAL_GPIO_ReadPin(pDIN_PAN_MODE_2_GPIO_Port,
			pDIN_PAN_MODE_2_Pin);
	if (!left) {*shape=SINE; }
	else if (!right) { *shape = SQUR; }
	else { *shape = TRI; }
}

uint32_t env_map(uint32_t env)
{
	// Cap env at ENV_MAX just in case it goes over
	if (env > ENV_MAX){
		env = ENV_MAX;
	}
	float fl_env = (float)env;
	return (uint32_t)(fl_env * (ADC_RESOLUTION) / ENV_MAX);
}

// TODO this is a bad function.
// -> Maybe can simplify by using a struct to reduce states
void sm_phase(StatePhase* state, EventPhase event, LED* LED_bypass){
	switch (*state) {
		case STATE_STD:
			if (event == EVENT_HARM){
				*state = STATE_HARM;
				HAL_DMA_Abort(&hdma_tim8_ch1);
				HAL_DMA_Start_IT(&hdma_tim8_ch1, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR1), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch2);
				HAL_DMA_Start_IT(&hdma_tim8_ch2, (uint32_t)dma_wavetable_b, (uint32_t)&(TIM3->CCR2), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch3_up);
				HAL_DMA_Start_IT(&hdma_tim8_ch3_up, (uint32_t)dma_wavetable_b, (uint32_t)&(TIM3->CCR3), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch4_trig_com);
				HAL_DMA_Start_IT(&hdma_tim8_ch4_trig_com, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR4), WAVETABLE_WIDTH);
				set_LED_color(LED_bypass, GREEN);
			}
			else if (event == EVENT_PAN){
				*state = STATE_PAN;
				HAL_DMA_Abort(&hdma_tim8_ch1);
				HAL_DMA_Start_IT(&hdma_tim8_ch1, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR1), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch2);
				HAL_DMA_Start_IT(&hdma_tim8_ch2, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR2), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch3_up);
				HAL_DMA_Start_IT(&hdma_tim8_ch3_up, (uint32_t)dma_wavetable_b, (uint32_t)&(TIM3->CCR3), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch4_trig_com);
				HAL_DMA_Start_IT(&hdma_tim8_ch4_trig_com, (uint32_t)dma_wavetable_b, (uint32_t)&(TIM3->CCR4), WAVETABLE_WIDTH);
				set_LED_color(LED_bypass, BLUE);

			}
			break;
		case STATE_HARM:
			if (event == EVENT_STD){
				*state = STATE_STD;
				HAL_DMA_Abort(&hdma_tim8_ch1);
				HAL_DMA_Start_IT(&hdma_tim8_ch1, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR1), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch2);
				HAL_DMA_Start_IT(&hdma_tim8_ch2, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR2), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch3_up);
				HAL_DMA_Start_IT(&hdma_tim8_ch3_up, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR3), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch4_trig_com);
				HAL_DMA_Start_IT(&hdma_tim8_ch4_trig_com, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR4), WAVETABLE_WIDTH);
				set_LED_color(LED_bypass, RED);
			}
			else if (event == EVENT_PAN){
				*state = STATE_PAN;
				HAL_DMA_Abort(&hdma_tim8_ch1);
				HAL_DMA_Start(&hdma_tim8_ch1, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR1), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch2);
				HAL_DMA_Start(&hdma_tim8_ch2, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR2), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch3_up);
				HAL_DMA_Start(&hdma_tim8_ch3_up, (uint32_t)dma_wavetable_b, (uint32_t)&(TIM3->CCR3), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch4_trig_com);
				HAL_DMA_Start(&hdma_tim8_ch4_trig_com, (uint32_t)dma_wavetable_b, (uint32_t)&(TIM3->CCR4), WAVETABLE_WIDTH);
				set_LED_color(LED_bypass, BLUE);
			}
			break;
		case STATE_PAN:
			if (event == EVENT_STD){
				*state = STATE_STD;
				HAL_DMA_Abort(&hdma_tim8_ch1);
				HAL_DMA_Start_IT(&hdma_tim8_ch1, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR1), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch2);
				HAL_DMA_Start_IT(&hdma_tim8_ch2, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR2), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch3_up);
				HAL_DMA_Start_IT(&hdma_tim8_ch3_up, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR3), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch4_trig_com);
				HAL_DMA_Start_IT(&hdma_tim8_ch4_trig_com, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR4), WAVETABLE_WIDTH);
				set_LED_color(LED_bypass, RED);

			}
			else if (event == EVENT_HARM){
				*state = STATE_HARM;
				HAL_DMA_Abort(&hdma_tim8_ch1);
				HAL_DMA_Start_IT(&hdma_tim8_ch1, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR1), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch2);
				HAL_DMA_Start_IT(&hdma_tim8_ch2, (uint32_t)dma_wavetable_b, (uint32_t)&(TIM3->CCR2), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch3_up);
				HAL_DMA_Start_IT(&hdma_tim8_ch3_up, (uint32_t)dma_wavetable_b, (uint32_t)&(TIM3->CCR3), WAVETABLE_WIDTH);
				HAL_DMA_Abort(&hdma_tim8_ch4_trig_com);
				HAL_DMA_Start_IT(&hdma_tim8_ch4_trig_com, (uint32_t)dma_wavetable_a, (uint32_t)&(TIM3->CCR4), WAVETABLE_WIDTH);
				set_LED_color(LED_bypass, GREEN);
			}
			break;

		default:
			break;
	}
}

void set_volume(uint16_t vol){
	float fl_vol = (float)(ADC_RESOLUTION - vol);
	float fl_vol_map = fl_vol * (VOL_MAP_MAX - VOL_MAP_MIN) / ADC_RESOLUTION;
	__HAL_TIM_SET_COMPARE(&htim2, TIM_CHANNEL_1, (uint16_t)fl_vol_map);
	__HAL_TIM_SET_COMPARE(&htim2, TIM_CHANNEL_2, (uint16_t)fl_vol_map);
}

// TODO implement with tap and external sync
// TODO add subdivision
void set_rate(float rate){
	//__HAL_TIM_SET_PRESCALER(&htim8, (uint32_t)rate);
	__HAL_TIM_SET_AUTORELOAD(&htim8, (uint32_t)rate);
}

void HAL_TIM_IC_CaptureCallback(TIM_HandleTypeDef *htim)
{

}

void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef* hadc)
{

}

void My_DMA_XferHalfCpltCallback(DMA_HandleTypeDef *hdma)
{
	// TODO don't call function from interrupt
	set_LED_state(&LED_tap, OFF);
	return;
}

void My_DMA_XferCpltCallback(DMA_HandleTypeDef *hdma)
{
	set_LED_state(&LED_tap, ON);
	return;
}


/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();

  HAL_GPIO_WritePin(pDOUT_LED2_B_GPIO_Port, pDOUT_LED2_B_Pin, LED_PIN_SET);
  HAL_GPIO_WritePin(pDOUT_LED2_R_GPIO_Port, pDOUT_LED2_R_Pin, LED_PIN_SET);
  HAL_GPIO_WritePin(pDOUT_LED2_G_GPIO_Port, pDOUT_LED2_G_Pin, LED_PIN_SET);
  HAL_GPIO_WritePin(pDOUT_LED1_B_GPIO_Port, pDOUT_LED1_B_Pin, LED_PIN_SET);
  HAL_GPIO_WritePin(pDOUT_LED1_R_GPIO_Port, pDOUT_LED1_R_Pin, LED_PIN_SET);
  HAL_GPIO_WritePin(pDOUT_LED1_G_GPIO_Port, pDOUT_LED1_G_Pin, LED_PIN_SET);

  while (1)
  {
	  HAL_Delay(250);

	  HAL_GPIO_TogglePin(pDOUT_LED2_B_GPIO_Port, pDOUT_LED2_B_Pin);
	  HAL_GPIO_TogglePin(pDOUT_LED2_R_GPIO_Port, pDOUT_LED2_R_Pin);
	  HAL_GPIO_TogglePin(pDOUT_LED2_G_GPIO_Port, pDOUT_LED2_G_Pin);
	  HAL_GPIO_TogglePin(pDOUT_LED1_B_GPIO_Port, pDOUT_LED1_B_Pin);
	  HAL_GPIO_TogglePin(pDOUT_LED1_R_GPIO_Port, pDOUT_LED1_R_Pin);
	  HAL_GPIO_TogglePin(pDOUT_LED1_G_GPIO_Port, pDOUT_LED1_G_Pin);

  }
  /* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
